### ISSUE TITLE
Crash happens when decode QR in a big size jpg image in Android. 

### ISSUE THREAD

**Issue by CellCS** [AifeiI/qr_code_tools#10]
If this image is jpg type, and size is around 20MB, will crash in **Android**.   There is no issue with a 25MB png file.

For iOS,  like iPadOS 14.5, works well. 

Env:
Plugin version: 0.0.7

Android:  tablet, Android 9.0.

[20MB JPG Image Sample](https://sample-videos.com/img/Sample-jpg-image-20mb.jpg)
<br>
[30MB JPG Image Sample](https://sample-videos.com/img/Sample-jpg-image-30mb.jpg)

```
....
E/AndroidRuntime(15350): java.lang.OutOfMemoryError: Failed to allocate a 840500016 byte allocation with 12582912 free bytes and 190MB until OOM, max allowed footprint 14148688, growth limit 201326592
E/AndroidRuntime(15350):        at com.aifeii.qrcode.tools.QrCodeToolsPlugin.onMethodCall(QrCodeToolsPlugin.kt:44)
E/AndroidRuntime(15350):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(15350):        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(15350):        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime(15350):        at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(15350):        at android.os.MessageQueue.next(MessageQueue.java:326)
E/AndroidRuntime(15350):        at android.os.Looper.loop(Looper.java:160)
E/AndroidRuntime(15350):        at android.app.ActivityThread.main(ActivityThread.java:6758)
E/AndroidRuntime(15350):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15350):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(15350):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process (15350): Sending signal. PID: 15350 SIG: 9
Lost connection to device.
```

**Comment by CellCS** [comment]
fixed by pull request #11
